FROM 963545387589.dkr.ecr.us-east-1.amazonaws.com/bluo/microtrader-base
MAINTAINER Bin Luo <bin_luo@timeinc.com>
LABEL application.component=microtrader-portfolio

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-portfolio-${app_version}-fat.jar /app/app.jar
